# Generated by Django 4.2.6 on 2023-10-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0002_category_description_category_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/path/to/default/image.jpg', upload_to='category'),
        ),
    ]
