# Generated by Django 4.2.6 on 2023-10-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0006_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
