# Generated by Django 4.2.6 on 2023-10-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
