# Generated by Django 4.2.6 on 2023-10-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0012_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
