# Generated by Django 4.2.6 on 2023-10-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0014_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
