# Generated by Django 4.2.4 on 2023-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0019_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner/img')),
                ('page_header', models.ImageField(upload_to='page_header/img')),
            ],
        ),
    ]
