# Generated by Django 4.2.4 on 2023-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0021_alter_banner_banner_alter_banner_page_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to='banner/img'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page_header',
            field=models.ImageField(upload_to='page_header/img'),
        ),
    ]
