# Generated by Django 4.2.4 on 2023-11-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0022_alter_banner_banner_alter_banner_page_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='page_header',
        ),
    ]
