# Generated by Django 4.2.4 on 2023-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0023_remove_banner_page_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
