# Generated by Django 4.2.4 on 2023-11-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0024_banner_subtitle_1_banner_subtitle_2_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
