# Generated by Django 4.2.6 on 2023-11-24 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0025_banner_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='New Offer')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_block', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(blank=True, to='admin_dash.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, to='admin_dash.offer'),
        ),
    ]
