# Generated by Django 4.2.6 on 2023-11-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0026_offer_category_offers_product_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_value',
            new_name='discount_amount',
        ),
    ]
