# Generated by Django 4.2.6 on 2023-11-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0027_rename_discount_value_offer_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dash.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dash.offer'),
        ),
    ]
