# Generated by Django 4.2.6 on 2023-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0028_remove_category_offers_remove_product_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
