# Generated by Django 4.2.4 on 2023-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0029_offer_is_valid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
