# Generated by Django 4.2.4 on 2023-11-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0030_delete_color_brand_is_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_amount',
            new_name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
    ]
