# Generated by Django 4.2.6 on 2023-12-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0031_rename_discount_amount_offer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_price',
        ),
    ]
