# Generated by Django 4.2.6 on 2023-12-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0032_remove_product_filter_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter_price',
        ),
    ]
