# Generated by Django 4.2.4 on 2023-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_alter_cart_created_at_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=150)),
                ('is_expired', models.BooleanField(default=False)),
                ('discound_amount', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=100)),
            ],
        ),
    ]
