# Generated by Django 4.2.4 on 2023-11-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Deliverd', 'Deliverd')], default='Pending', max_length=150),
        ),
    ]
