# Generated by Django 4.2.4 on 2023-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
