# Generated by Django 4.2.4 on 2023-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_discount_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Deliverd', 'Deliverd'), ('Cancel', 'Cancel')], default='Order Confirmed', max_length=150),
        ),
    ]
