# Generated by Django 4.2.6 on 2023-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
